name: CI
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: docker build -t aldos/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true aldos/react-test npm run test -- --coverage

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: aldos/multi-client:latest

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: aldos/multi-nginx:latest

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: aldos/multi-server:latest

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          push: true
          tags: aldos/multi-worker:latest

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-af-south-1-104599259837
          region: af-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip